# Config file for automatic testing at travis-ci.org
sudo: false

language: python

matrix:
  include:
    - python: 2.7
      env: TEST_MODE=TESTS
    #- python: 2.7
    #  env: TEST_MODE=PEP8

install:
  source build_tools/install.sh

script:
  bash build_tools/test_script.sh

#after_success:
#    # Report coverage results to codecov.io
#    # and export tox environment variables
#    - pip install codecov
#    - codecov -e TOX_ENV TRAVIS_OS_NAME
